name: Publish Custom App

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Retrieving custom app configuration
        uses: actions/checkout@v3

      - name: Retrieving Kiwix Android source code
        run: git clone --depth=1 --single-branch --branch develop https://github.com/kiwix/kiwix-android.git

      - name: Copying custom app configuration into Kiwix Android code base
        run: ./copy_files_to_kiwix_android.sh

      - name: Preparing signing material
        env:
          keystore: ${{ secrets.keystore }}
          google_json: ${{ secrets.google_json }}
        run: |
          echo "$google_json" | base64 -d > kiwix-android/google.json
          echo "$keystore" | base64 -d > kiwix-android/kiwix-android.keystore
      

      - name: Publishing app to Google Play
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          cd kiwix-android
          echo "TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
          eval "./gradlew publishWIKIMEDReleaseApkWithExpansionFile"
